import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/components/footer";
import Navbar from "@/components/navbar";
import { ThemeModeScript } from "flowbite-react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) { 
  return (
    <html lang="en">
      <head>
        <ThemeModeScript />
      </head>
      <body className={` ${inter.className}`}>
          <main className="min-h-screen items-center justify-between box-border max-w-screen-2xl m-auto relative">
            <Navbar />
            <div className="container-2xl">
              <div>
                {children}
              </div>
            </div>
            <Footer />
          </main>
      </body>
    </html>
  );
}
